### ISSUE TITLE
table splicing 

### ISSUE THREAD

**Issue by neeasade** [neeasade/gott#7]
thinking special key `-`:

``` toml
[subtable]
a = "{{.ok}}"

[table]
ok = "foo"
- = ["subtable"]
```

=> `.table.a = "foo"`
